# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

boxes = [
    {
        :name => "vagrant-master-1",
        :eth1 => "192.168.56.10",
        :mem => "4096",
        :cpu => "2"
    },
    {
        :name => "vagrant-worker-1",
        :eth1 => "192.168.56.20",
        :mem => "2048",
        :cpu => "1"
    },
    {
        :name => "vagrant-om-1",
        :eth1 => "192.168.56.30",
        :mem => "10240",
        :cpu => "4"
    }
]

$change_sshd_config = <<-SCRIPT
echo change sshd_config to allow public key authentication and relaod sshd...
sed -i 's/\#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/\#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl restart sshd
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"
  config.ssh.username = "root"
  config.ssh.password = "vagrant"
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = opts[:mem]
        v.vmx["numvcpus"] = opts[:cpu]
      end
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end
      config.vm.network :private_network, ip: opts[:eth1]
    end
  end
  config.vm.provision "shell", inline: $change_sshd_config
end

